#!/usr/bin/env node

const fs = require('fs');

const conventionalCommitMessageRegExp =
  /^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([\w\-\.]+\))?(!)?: ([\w ])+([\s\S]*)/g;
let exitCode = 0;
const commitMsgFile = process.argv[2];
const message = fs.readFileSync(commitMsgFile, 'utf8');
const isValid = conventionalCommitMessageRegExp.test(message);

if (!isValid) {
  console.error(
    'Cannot commit: the commit message does not comply with conventional commits standards. Please check https://gist.github.com/qoomon/5dfcdf8eec66a051ecd85625518cfd13',
  );
  exitCode = 1;
}

process.exit(exitCode);
